- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: remove old app content
  ansible.builtin.file:
    path: /app
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory


