- name: Install python deps
  ansible.builtin.yum:
    name: python3-pymysql
    state: installed

- name: load mysql schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/{{component}}.sql
    login_host: mysql-dev.davedevops.tech
    login_user: root
    login_password: "{{ root_mysql_password }}"
