groups:
  - name: Alerts
    rules:
      - alert: :InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance Down - [{{ $label.name}}]"
          description: "Instance Down - [{{ $label.name}}]"